#每周1，4，6自动更新refresh_token
name: Update Token

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '10 10 * * 1,4,6'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and nacl #安装requests和nacl模块
      run: |
        pip install requests
        pip install PyNaCl
    - name: update secrets #更新token到secret
      env: 
        #github的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        #以下是微软的账号信息（修改以下，类推复制增加）
        APP_NUM: ${{ secrets.APP_NUM }} 
        REDIRECT_URI: ${{ secrets.REDIRECT_URL }}
        #账号/应用1
        MS_TOKEN_1: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID_1: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET_1: ${{ secrets.CLIENT_SECRET }}
        #账号/应用2
        MS_TOKEN_2: ${{ secrets.MS_TOKEN_2 }} 
        CLIENT_ID_2: ${{ secrets.CLIENT_ID_2 }}
        CLIENT_SECRET_2: ${{ secrets.CLIENT_SECRET_2 }}
        #账号/应用3
        MS_TOKEN_3: ${{ secrets.MS_TOKEN_3 }} 
        CLIENT_ID_3: ${{ secrets.CLIENT_ID_3 }}
        CLIENT_SECRET_3: ${{ secrets.CLIENT_SECRET_3 }}
        #账号/应用4
        MS_TOKEN_4: ${{ secrets.MS_TOKEN_4 }} 
        CLIENT_ID_4: ${{ secrets.CLIENT_ID_4 }}
        CLIENT_SECRET_4: ${{ secrets.CLIENT_SECRET_4 }}
        #账号/应用5
        MS_TOKEN_5: ${{ secrets.MS_TOKEN_5 }} 
        CLIENT_ID_5: ${{ secrets.CLIENT_ID_5 }}
        CLIENT_SECRET_5: ${{ secrets.CLIENT_SECRET_5 }}
        #如此类推，自己复制增加账号/应用
        MS_TOKEN_6: ${{ secrets.MS_TOKEN_6 }} 
        CLIENT_ID_6: ${{ secrets.CLIENT_ID_6 }}
        CLIENT_SECRET_6: ${{ secrets.CLIENT_SECRET_6 }}

        MS_TOKEN_7: ${{ secrets.MS_TOKEN_7 }} 
        CLIENT_ID_7: ${{ secrets.CLIENT_ID_7 }}
        CLIENT_SECRET_7: ${{ secrets.CLIENT_SECRET_7 }}

        MS_TOKEN_8: ${{ secrets.MS_TOKEN_8 }} 
        CLIENT_ID_8: ${{ secrets.CLIENT_ID_8 }}
        CLIENT_SECRET_8: ${{ secrets.CLIENT_SECRET_8 }}

        MS_TOKEN_9: ${{ secrets.MS_TOKEN_9 }} 
        CLIENT_ID_9: ${{ secrets.CLIENT_ID_9 }}
        CLIENT_SECRET_9: ${{ secrets.CLIENT_SECRET_9 }}

        MS_TOKEN_10: ${{ secrets.MS_TOKEN_10 }} 
        CLIENT_ID_10: ${{ secrets.CLIENT_ID_10 }}
        CLIENT_SECRET_10: ${{ secrets.CLIENT_SECRET_10 }}

        MS_TOKEN_11: ${{ secrets.MS_TOKEN_11 }} 
        CLIENT_ID_11: ${{ secrets.CLIENT_ID_11 }}
        CLIENT_SECRET_11: ${{ secrets.CLIENT_SECRET_11 }}

        MS_TOKEN_12: ${{ secrets.MS_TOKEN_12 }} 
        CLIENT_ID_12: ${{ secrets.CLIENT_ID_12 }}
        CLIENT_SECRET_12: ${{ secrets.CLIENT_SECRET_12 }}

        MS_TOKEN_13: ${{ secrets.MS_TOKEN_13 }} 
        CLIENT_ID_13: ${{ secrets.CLIENT_ID_13 }}
        CLIENT_SECRET_13: ${{ secrets.CLIENT_SECRET_13 }}

        MS_TOKEN_14: ${{ secrets.MS_TOKEN_14 }} 
        CLIENT_ID_14: ${{ secrets.CLIENT_ID_14 }}
        CLIENT_SECRET_14: ${{ secrets.CLIENT_SECRET_14 }}

        MS_TOKEN_15: ${{ secrets.MS_TOKEN_15 }} 
        CLIENT_ID_15: ${{ secrets.CLIENT_ID_15 }}
        CLIENT_SECRET_15: ${{ secrets.CLIENT_SECRET_15 }}

        MS_TOKEN_16: ${{ secrets.MS_TOKEN_16 }} 
        CLIENT_ID_16: ${{ secrets.CLIENT_ID_16 }}
        CLIENT_SECRET_16: ${{ secrets.CLIENT_SECRET_16 }}

        MS_TOKEN_17: ${{ secrets.MS_TOKEN_17 }} 
        CLIENT_ID_17: ${{ secrets.CLIENT_ID_17 }}
        CLIENT_SECRET_17: ${{ secrets.CLIENT_SECRET_17 }}

        MS_TOKEN_18: ${{ secrets.MS_TOKEN_18 }} 
        CLIENT_ID_18: ${{ secrets.CLIENT_ID_18 }}
        CLIENT_SECRET_18: ${{ secrets.CLIENT_SECRET_18 }}

        MS_TOKEN_19: ${{ secrets.MS_TOKEN_19 }} 
        CLIENT_ID_19: ${{ secrets.CLIENT_ID_19 }}
        CLIENT_SECRET_19: ${{ secrets.CLIENT_SECRET_19 }}

        MS_TOKEN_20: ${{ secrets.MS_TOKEN_20 }} 
        CLIENT_ID_20: ${{ secrets.CLIENT_ID_20 }}
        CLIENT_SECRET_20: ${{ secrets.CLIENT_SECRET_20 }}

        MS_TOKEN_21: ${{ secrets.MS_TOKEN_21 }} 
        CLIENT_ID_21: ${{ secrets.CLIENT_ID_21 }}
        CLIENT_SECRET_21: ${{ secrets.CLIENT_SECRET_21 }}

        MS_TOKEN_22: ${{ secrets.MS_TOKEN_22 }} 
        CLIENT_ID_22: ${{ secrets.CLIENT_ID_22 }}
        CLIENT_SECRET_22: ${{ secrets.CLIENT_SECRET_22 }}

        MS_TOKEN_23: ${{ secrets.MS_TOKEN_23 }} 
        CLIENT_ID_23: ${{ secrets.CLIENT_ID_23 }}
        CLIENT_SECRET_23: ${{ secrets.CLIENT_SECRET_23 }}

        MS_TOKEN_24: ${{ secrets.MS_TOKEN_24 }} 
        CLIENT_ID_24: ${{ secrets.CLIENT_ID_24 }}
        CLIENT_SECRET_24: ${{ secrets.CLIENT_SECRET_24 }}

        MS_TOKEN_25: ${{ secrets.MS_TOKEN_25 }} 
        CLIENT_ID_25: ${{ secrets.CLIENT_ID_25 }}
        CLIENT_SECRET_25: ${{ secrets.CLIENT_SECRET_25 }}

        MS_TOKEN_26: ${{ secrets.MS_TOKEN_26 }} 
        CLIENT_ID_26: ${{ secrets.CLIENT_ID_26 }}
        CLIENT_SECRET_26: ${{ secrets.CLIENT_SECRET_26 }}

        MS_TOKEN_27: ${{ secrets.MS_TOKEN_27 }} 
        CLIENT_ID_27: ${{ secrets.CLIENT_ID_27 }}
        CLIENT_SECRET_27: ${{ secrets.CLIENT_SECRET_27 }}

        MS_TOKEN_28: ${{ secrets.MS_TOKEN_28 }} 
        CLIENT_ID_28: ${{ secrets.CLIENT_ID_28 }}
        CLIENT_SECRET_28: ${{ secrets.CLIENT_SECRET_28 }}

        MS_TOKEN_29: ${{ secrets.MS_TOKEN_29 }} 
        CLIENT_ID_29: ${{ secrets.CLIENT_ID_29 }}
        CLIENT_SECRET_29: ${{ secrets.CLIENT_SECRET_29 }}

        MS_TOKEN_30: ${{ secrets.MS_TOKEN_30 }} 
        CLIENT_ID_30: ${{ secrets.CLIENT_ID_30 }}
        CLIENT_SECRET_30: ${{ secrets.CLIENT_SECRET_30 }}

        MS_TOKEN_31: ${{ secrets.MS_TOKEN_31 }} 
        CLIENT_ID_31: ${{ secrets.CLIENT_ID_31 }}
        CLIENT_SECRET_31: ${{ secrets.CLIENT_SECRET_31 }}

        MS_TOKEN_32: ${{ secrets.MS_TOKEN_32 }} 
        CLIENT_ID_32: ${{ secrets.CLIENT_ID_32 }}
        CLIENT_SECRET_32: ${{ secrets.CLIENT_SECRET_32 }}
      run: |
        python UpdateToken.py
